config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :foods, expect: [:update]

  authenticated :user do
    root 'recipes#index', as: :authenticated_root
  end

  root 'home#index'

  resources :recipes do
    resources :recipe_foods
    member do
      get 'generate_shopping_list', to: 'recipes#generate_shopping_list'
    end
    collection do
      get 'public_recipes', to: 'recipes#public_recipes'
    end
  end
  
  resources :users
  put '/recipes/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_recipe_public'

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: true
  validates :cooking_time, numericality: { greater_than: 0 }
  validates :preparation_time, numericality: { greater_than: 0 }
  validates :user_id, presence: true

  scope :public_recipes, -> { where(public: true).order(created_at: :desc) }

  def toggle_public
    update(public: !public)
  end

  def add_to_shopping_list
    update(add_to_shopping_list: !add_to_shopping_list)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_path, notice: 'Access denied'
  end

  def index
    if current_user
      @recipes = current_user.recipes.includes(:recipe_foods).order(created_at: :desc)
    else
      redirect_to new_user_session_path, alert: 'Please log in to view your foods.'
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @food_recipe = RecipeFood.where(recipe_id: @recipe.id).includes([:food])
  end

  def new
    @recipe = Recipe.new
  end

  def edit; end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.toggle!(:public)
    redirect_to @recipe
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Impressive!' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, notice: 'Whoops Oh Dear!' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Impressive!' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, notice: 'Whoops Oh Dear!' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # delete
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Impressive!' }
      format.json { head :no_content }
    end
  end

  def public_recipes
    @recipes = Recipe.where(public: true).order(created_at: :desc)
  end

  def generate_shopping_list
    @total_value = 0
    food_types = Food.all.includes(:recipe_foods).order(created_at: :desc)
    food_types.each do |food|
      # food.update_quantity
      @total_value += food.quantity * food.price
    end
    @foods = Food.where('quantity != 0')
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :description, :public, :cooking_time)
  end
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, html: { class: "recipe-form-container" }) do |form| %>
  <% if recipe.errors.any? %>
    <div class="recipe-error-messages">
      <h2><%= pluralize(recipe.errors.count, "error") %> cannot save recipe:</h2>
      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <section class="form_container">
    <div class="input_group">
      <%= form.label :name, class: "form_label" %>
      <%= form.text_field :name, class: "form_input" %>
    </div>
    <div class="input_group">
      <%= form.label :preparation_time, class: "form_label" %>
      <%= form.number_field :preparation_time, class: "form_input" %>
    </div>
    <div class="input_group">
      <%= form.label :cooking_time, class: "form_label" %>
      <%= form.number_field :cooking_time, class: "form_input" %>
    </div>
    <div class="input_group">
      <%= form.label :description, class: "form_label" %>
      <%= form.text_area :description, class: "form_input" %>
    </div>
    <div  class="submit">
      <%= form.submit "Save Recipe", class: "btn btn-success" %>
    </div>
  </section>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="recipe_details">
  <div class="left_container">
    <div class="recipe_name">
      <%= link_to recipe.name, recipe, class: "recipe_link" %>
    </div>
    <div class="remove-btn">
      <%= button_to "REMOVE", recipe, method: :delete, class: "btn btn-danger" %>
    </div>
  </div>
  <div class="right_container">
    <div class="recipe_description">
      <%= recipe.description %>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="edit-recipe-container">
  <h1 class="edit-recipe-title">Editing recipe</h1>

  <%= render "form", recipe: @recipe %>

  <div class="edit-recipe-links">
    <%= link_to "Show this recipe", @recipe, class: "edit-recipe-link" %> |
    <%= link_to "Back to recipes", recipes_path, class: "edit-recipe-link" %>
  </div>
</div>

app/views/recipes/generate_shopping_list.html.erb
<div class="detail_container">
  <h2 class="page_title">Shopping List</h2>
  <div class="shopping_summary">
    <p>Amount of food items to buy: <%= @foods.length%></p>
    <p>Total value of food needed: <%= @total_value%></p>
  </div>
  <table class="table">
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Price</th>
    </tr>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.quantity %> <%= food.measurement_unit %></td>
        <td>$ <%= food.price * food.quantity %></td>
      </tr>
    <% end %>
  </table>
  <%= link_to 'Back to Recipes', recipes_path, class: "btn btn-white back_button" %>
</div>

app/views/recipes/index.html.erb
<div class="page_container">
  <% if notice.present? %>
    <p class="notification notice"><%= notice %></p>
  <% end %>
  <h1 class="page_title">Recipes</h1>
  <div class="recipes_list" id="recipes">
    <% if @recipes.any? %>
      <% @recipes.each do |recipe| %>
        <%= render recipe %>
      <% end %>
    <% else %>
      <p class="no-recipes">No recipes found.</p>
    <% end %>
  </div>
  <div class="new-recipe-link">
    <%= link_to "New Recipe", new_recipe_path, class: "btn btn-success new_btn" %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="page_container add_item">
  <h1 class="page_title">Add New Recipe</h1>
  <%= render "form", recipe: @recipe %>
  <%= link_to 'Back to Recipes', recipes_path, class: "btn btn-white back_button" %>
</div>

app/views/recipes/public_recipes.html.erb
<div class="page_container">
  <h1 class="page_title">Public Recipes</h1>
  <% @recipes.each do |recipe| %>
    <div class="recipe_card">
      <div class="recipe_card_left">
        <h5 class="name"><%= recipe.name %></h5>
        <h6>By: <%= recipe.user.name %></h6>
      </div>
      <div class="recipe_card_right">
        <p>Total food items: <%= recipe.recipe_foods.length %></p>
        <% total_price = 0 %>
        <% recipe.recipe_foods.each do |ingredient| %>
          <% total_price += ingredient.quantity * ingredient.food.price %>
        <% end %>
        <p>Total price: $ <%= total_price %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="detail_container">
  <h2 class="page_title"><%= @recipe.name %></h2>
  <div class="recipe_box">
    <div class="recipe_box_left">
      <p>Preparation time: <%= @recipe.preparation_time %> min</p>
      <d>Cooking time: <%= @recipe.cooking_time %> min</p>
      <p>Steps go here...</p>
    </div>
    <div class="recipe_box_right">
      <% if can? :update, @recipe %>
        <div class="form-check form-switch d-flex align-items-center">
          <label class="form-check-label me-2" for="public-switch">Public&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
          <input class="form-check-input" type="checkbox" id="public-switch" <%= @recipe.public? ? 'checked' : '' %>>
        </div>
      <% end %>
    </div>
  </div>
  <div class="link_btn">
    <div><%= link_to "Generate Shopping List", generate_shopping_list_recipe_path(@recipe), class: "btn btn-success" %></div>
    <div><%= link_to "Add Ingredient" , new_recipe_recipe_food_path(@recipe.id), class: "btn btn-success" %></div>
  </div>
  <hr style= "width:55%">
  <div id="ingredient_table">
    <table class="table">
      <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Value</th>
          <% if can? :destroy, @recipe %>
            <th>Actions</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @food_recipe.each do |recipe_food| %>
          <tr id="<%= dom_id recipe_food %>">
            <td><%= recipe_food.food.name %></td>
            <td><%= recipe_food.quantity %></td>
            <td><%= recipe_food.food.price * recipe_food.quantity %></td>
            <% if can? :destroy, @recipe %>
              <td>
                <%= link_to "Modify", edit_recipe_recipe_food_path(@recipe, recipe_food), class: "btn btn-info text-white" %>
                <%= link_to "Delete", recipe_recipe_food_path(@recipe, recipe_food), class: "btn btn-danger", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= link_to 'Back to Recipes', recipes_path, class: "btn btn-white back_button" %>
</div>