config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :foods, expect: [:update]

  authenticated :user do
    root 'recipes#index', as: :authenticated_root
  end

  root 'home#index'

  resources :recipes do
    resources :recipe_foods
    member do
      get 'generate_shopping_list', to: 'recipes#generate_shopping_list'
    end
    collection do
      get 'public_recipes', to: 'recipes#public_recipes'
    end
  end
  
  resources :users
  put '/recipes/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_recipe_public'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="custom-navbar">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "RecipeApp", root_path, class: "navbar-brand custom-brand" %>
    </div>
    <div class="navbar-menu">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Foods", foods_path, class: "nav-link custom-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Food", new_food_path, class: "nav-link custom-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Recipes", recipes_path, class: "nav-link custom-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Public Recipes", public_recipes_recipes_path, class: "nav-link custom-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link custom-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: "nav-link custom-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link custom-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
</nav>

app/views/home/index.html.erb
<div class="welcome-container">
  <div class="welcome-content">
    <h1 class="welcome-heading">Welcome to RecipeApp</h1>
    <p class="welcome-text">Discover a World of Delicious Recipes</p>
    <a href="<%= recipes_path %>" class="btn btn-success explore-button">Explore Recipes</a>
  </div>
</div>