config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :foods, expect: [:update]

  authenticated :user do
    root 'recipes#index', as: :authenticated_root
  end

  root 'home#index'

  resources :recipes do
    resources :recipe_foods
    member do
      get 'generate_shopping_list', to: 'recipes#generate_shopping_list'
    end
    collection do
      get 'public_recipes', to: 'recipes#public_recipes'
    end
  end
  
  resources :users
  put '/recipes/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_recipe_public'

end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  # load_and_authorize_resource
  # rescue_from CanCan::AccessDenied do |_exception|
  # redirect_to root_path, notice: 'Access denied'
  # end

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.where.not(id: RecipeFood.where(recipe_id: @recipe.id).pluck(:food_id))

    @recipe_food = RecipeFood.new
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = Recipe.find(params[:recipe_id])
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new(recipe_food_params)
    if @recipe_food.save
      redirect_to recipe_path(@recipe), notice: 'Ingredient successfully added.'
    else
      puts @recipe_food.errors.full_messages
      render 'new'
    end
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = @recipe_food.recipe

    if @recipe_food.update(recipe_food_params)
      redirect_to recipe_path(@recipe), notice: 'Ingredient successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = @recipe_food.recipe
    if @recipe_food.destroy
      redirect_to recipe_path(@recipe), notice: 'Ingredient successfully removed.'
    else
      redirect_to recipe_path(@recipe), alert: 'Failed to remove ingredient.'
    end
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :recipe_id, :quantity)
  end
end

app/views/recipe_foods/edit.html.erb
<div class="page_container">
  <div class="food-recipe-container">
    <h3 class="page_title"> Edit Ingredient</h3>
    <table class="table">
      <tr>
        <th>Food</th>
        <th>Measurement Unit</th>
        <th>Unit Price</th>
        <th>Actions</th>
      </tr>
      <tr>
        <td><%= @recipe_food.food.name %></td>
        <td><%= @recipe_food.food.measurement_unit %></td>
        <td>$ <%= @recipe_food.food.price %></td>
        <td>
          <%= form_with model: @recipe_food, url: recipe_recipe_food_path(@recipe,@recipe_food)  do |f| %>
            <%= f.number_field :quantity, value: @recipe_food.quantity %>
            <%= f.submit "Modify", class:"btn btn-warning btn-sm" %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
</div>

app/views/recipe_foods/new.html.erb
<div class="page_container">
  <div class="food-recipe-container">
    <h2 class="page_title">Add New Ingredients</h2>
    <h4><%=@recipe.name%></h4>
    <table class="table">
      <tr>
        <th>Food</th>
        <th>Measurement Unit</th>
        <th>Unit Price</th>
        <th>Actions</th>
      </tr>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.measurement_unit %></td>
          <td>$ <%= food.price %></td>
          <td>
            <%= form_with model: @recipe_food, url: recipe_recipe_foods_path(@recipe) do |f| %>
              <%= f.hidden_field :recipe_id, value: @recipe.id %>
              <%= f.hidden_field :food_id, value: food.id %>
              <%= f.number_field :quantity, value: 0 %>
              <%= f.submit "Add", class:"btn btn-success btn-sm" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>